# my first github actions file
name: sample

on:
  push:
    branches:
      - main

jobs:
  samplerun:
    runs-on: ubuntu-latest
    steps:
      - name: avinash
        env:
          firstname: garikipati
          secondname: avinash
        run: |
          echo "hello there I'm $firstname $secondname"  